<!DOCTYPE html>

<html>
<head>
<meta http-equiv="content-type" name="text/html;charset=utf-8">
<link rel="stylesheet" type="text/css" href="/blog/blog/public/css/log/index.css">
<link rel="stylesheet" type="text/css" href="/blog/blog/public/css/bootstrap.css">
<script type="text/javascript" src="/blog/blog/public/js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="/blog/blog/public/js/bootstrap.js"></script>
</head>
<body>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->




<div class="header">
	<div class="center">
	  <ul class="nav nav-tabs navbar-inverse" contenteditable="true">
	                  <li class="active"><a href="#">首页</a></li>
	                  <li><a href="#">个人信息</a></li>
	                  <li><a href="#">日志</a>
	                </ul>
	</div>
</div>
<div class="main">
   <form name="logsubmit" method="post" action="save">
<div class="input-group subject">
  <span class="input-group-addon">subject:</span>
  <input name="subject" type="text" class="form-control" placeholder="Subject">
</div>
<div class="content">

  <input name="content" type="text" class="content">
</div>
<div class="submit btn-group">
<input type="submit" name="submit" value="提交" class="btn btn-default">
</div>

</form>
</div>
<div class="footer">


</div>


</body>
</html>