<!DOCTYPE html>

<html>
<head>
<meta http-equiv="content-type" name="text/html;charset=utf-8">
<link rel="stylesheet" type="text/css" href="/blog/public/css/login.css">
<link rel="stylesheet" type="text/css" href="/blog/public/css/bootstrap.css">
<script type="text/javascript" src="/blog/public/js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="/blog/public/js/bootstrap.js"></script>
</head>
<body>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->




<div class="header">
	<div class="center">
	  <ul class="nav nav-tabs navbar-inverse" contenteditable="true">
	                  <li class="active"><a href="#">首页</a></li>
	                  <li><a href="#">个人信息</a></li>
	                  <li><a href="#">日志</a>
	                </ul>
	</div>
</div>
<div class="main">
   <div class="left">
   	    <form class="form-horizontal" name="login" method="post" action="index">
		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-3 control-label">用户名</label>
		    <div class="col-sm-8">
		      <input name="username" type="email" class="form-control" id="inputEmail3" placeholder="User">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="inputPassword3" class="col-sm-3 control-label">密码</label>
		    <div class="col-sm-8">
		      <input name="password" type="password" class="form-control" id="inputPassword3" placeholder="Password">
		    </div>
		  </div>
		  <div class="form-group">
		    <div class="col-sm-offset-3 col-sm-8">
		      <div class="checkbox">
		        <label>
		          <input type="checkbox"> 记住我
		        </label>
		      </div>
		    </div>
		  </div>
		  <div class="form-group">
		    <div class="col-sm-offset-3 col-sm-8">
		      <button type="submit" class="btn btn-default">登录</button>
		    </div>
		  </div>
		</form>
   </div>
   <div class="right">
		   <div class="bs-example">
			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		 			 <!-- Indicators -->
					  <ol class="carousel-indicators">
					    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
					    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
					  </ol>
		
		  <!-- Wrapper for slides -->
		  <div class="carousel-inner">
			    <div class="item active">
			      <img src="/blog/public/img/23.jpg" alt="...">
			      <div class="carousel-caption">
			        <p>音乐厅 </p>
			      </div>
			    </div>
			      <div class="item">
			      <img src="/blog/public/img/24.jpg" alt="...">
			      <div class="carousel-caption">
			        <p>教学楼</p>
			      </div>
			     </div>
			      <div class="item">
			      <img src="/blog/public/img/25.jpg" alt="...">
			      <div class="carousel-caption">
			        <p>体育馆</p>
			      </div>
			    </div>
		    
		  </div>
		
		  <!-- Controls -->
		  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left"></span>
		  </a>
		  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
		    <span class="glyphicon glyphicon-chevron-right"></span>
		  </a>
		</div>
  </div>
</div>
  
</div>
<div class="footer">


</div>


</body>
</html>