<!DOCTYPE html>

<html>
<head>
<meta http-equiv="content-type" name="text/html;charset=utf-8">
<link rel="stylesheet" type="text/css" href="/blog/blog/public/css/User/index.css">
<link rel="stylesheet" type="text/css" href="/blog/blog/public/css/bootstrap.css">
<script type="text/javascript" src="/blog/blog/public/js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="/blog/blog/public/js/bootstrap.js"></script>
<script type="text/javascript">
$(document).ready(function(){

	$("#upload").change(function() {
 		
 	 	var path = $("#upload").val();//C:\\fakepath\\xxx";
 	 	//alert(path);
 		var full_path = path.replace(/C:\\fakepath/, "\\blog\\blog\\public\\img");
 		//alert(full_path);
 		//alert($("#upload").val());
	    $("#image").attr("src",full_path);
		 //document.getElementById("image").src = this.value;
	});
		
});


</script>
<style type="text/css">
table
{
	border:1px solid red;
}
td {
	margin:0px;
	padding:0px;
	width:230px;
	height:70px;
	border:1px solid black;
}
.main {
	margin:5px;
}
input.right {
	margin-right:0px;
}
</style>
</head>
<body>
<div class="header">
	<div class="center">
	  <ul class="nav nav-tabs navbar-inverse" contenteditable="true">
	                  <li class="active"><a href="#">首页</a></li>
	                  <li><a href="#">个人信息</a></li>
	                  <li><a href="#">日志</a>
	                </ul>
	</div>
</div>
<div class="main">

<form action="save" method="post" enctype="multipart/form-data">
<table>
<tr>
<td><span>用户名:<input class="right" name="username" type="text" value="<?php echo "$username"?>"> </span></td>
<td><span >年龄：<input class="right" name="age" type="text"></span></td> 
<td rowspan="3"><span style="margin:0px;padding:0px;">
<input id="image" style="height:100%;width:100%;" name="image" type="image" src="<?php echo 'hex2bin($image)';?>" alt="个人相片"></span>
</td>
</tr>

<tr>
	<td>
	<span style="padding:0px;margin:0px;">邮箱:<input class="right" name="email" type="text"></span>
	</td>
	<td>
	<span>
		性别:<input class="right" name="sex" type="radio"  value="0">男
		<input class="right" name="sex" type="radio" value="1">女
	</span>
	</td>
</tr>
<tr >
<td>
<span>家庭地址：</span><input name="address" type="text">
</td>
<td> 
<span>密码:</span><input name="password" type="password">
</td>


</tr>
<tr>
<td colspan="2">
<input type="submit" name="submit" value="提交"/>
<input type="reset" value="重置"/>
</td>
<td>
<input type="file" id="upload" name="file" value="上传" />
</td>
</tr>
</table>

</form>
</div>
<div class="footer">


</div>


</body>
</html>