<!DOCTYPE html>

<html>
<head>
<meta http-equiv="content-type" name="text/html;charset=utf-8">
<link rel="stylesheet" type="text/css" href="/blog/public/css/register.css">
<link rel="stylesheet" type="text/css" href="/blog/public/css/bootstrap.css">
<script type="text/javascript" src="/blog/public/js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="/blog/public/js/bootstrap.js"></script>
</head>
<body>
<div class="header">
	<div class="center">
	  <ul class="nav nav-tabs navbar-inverse" contenteditable="true">
	                  <li><a href="/blog/login/login">首页</a></li>
	                  <li><a href="#">个人信息</a></li>
	                  <li><a href="#">日志</a>
	                </ul>
	</div>
</div>
<div class="main">
<form name="register" action="register" method="post">
 <p><span>username:</span>
<input type="email" name="username">
</p>
<p><span>password:</span><input type="password" name="password"/></p>
<p><input type="submit" value="提交" name="submit"/></p>
</form>
  
</div>
<div class="footer">


</div>

</body>
</html>